# Generated by Django 3.1.5 on 2021-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='incomming_dsrc_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=1000)),
            ],
        ),
    ]
