# Generated by Django 3.1.5 on 2021-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cav_fe', '0001_Munal_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomming_dsrc_message',
            name='value',
            field=models.CharField(max_length=150),
        ),
    ]
